apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anki-sync-server-pvc
  namespace: anki-sync-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
